### PR TITLE
Google Calendar Feature

### PR DESCRIPTION
**Pull request by DenizUgur**
Title explains a lot 😄 . in lateBackground.mc ClientId, ClientSecret and CalendarId is omitted. I can mail the credentials to you. I strongly recommend you to read these values from a json file which you can include in .gitignore.

### CODE REVIEW

**Comment by myneur** [comment]
Awesome, let's experiment with it! Would you send me the info to my profile mail how to incorporate the ClientId, ClientSecret and CalendarId or how to test it? 
I can surely .gitignore it…
Thank you!

PS: I'm not sure I'm merging it right into the master, I'm more a designer than a programmer, but I'm happy we can experiment with that together:)

**Comment by DenizUgur** [comment]
I've checked the concept design again and I've missed the location and "relax" calendar etc.
Let me know when you finish the design I'll add them too.

**Comment by myneur** [comment]
Wow, you are fast @DenizUgur, I can not keep up with it:)
The designs are ready: 
calendar
(we can skip the other metrics for now and keep just the calendar to test it)

For the strong Flavor, there will be a need to switch sunrise/sunset position with the ring: 
bold extreme

Let's focus on proving the calendar works first reliably… 

Awesome work!

**Comment by myneur** [comment]
… and then the final would be the full concept of showing the full day events. I might just revisit the colors. That has time. Even just showing the next event is the most valuable. 
calendar full

**Comment by DenizUgur** [comment]
All 3 designs look pretty awesome. It would be great to release all of them and make an option to choose between them.

**Pull request merged**
